;;; Automatically generated by ‘recentf’ on Sat Mar 15 16:34:00 2025.

(setq recentf-list
      '(
        "~/.tmux.conf"
        "~/CodeSpace/ws_rs/blog_system/src/main.rs"
        "~/.config/waybar/config.jsonc"
        "~/.config/ghostty/config"
        "~/.config/starship.toml"
        "~/.config/nvim/lua/guolisen/plugins/oil.lua"
        "~/CodeSpace/ws_rs/rs_if_let/src/main.rs"
        "~/.emacs.d/emacs-config.org"
        "~/Org/notes/20250301T233053--hello-world__economics.org"
        "~/CodeSpace/ws_rs/rs_rc/src/main.rs"
        "~/env/.emacs.d/emacs-config.org"
        "~/.viminfo"
        "~/Org/notes/20250301T230213--hello-world__emacs.org"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
